apiVersion: v1
kind: ConfigMap
metadata:
  name: appfastfood-configmap
data:
  MONGODB_URI: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/?ssl=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
  MONGODB_HOST: fastfood-docdb2-cluster.cluster-c4bgv5fkmppp.us-east-1.docdb.amazonaws.com
  MONGODB_PORT: 27017
  MONGODB_DATABASE: appfastfood
  JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"
