services:
  app-techchallenge-fastfood:
    build: 
      context: .
      dockerfile: Dockerfile
    image: app-fastfood-gp24:${VERSAO}
    networks:
      - techchallenge-fastfood-net
    ports:
      - "8080:8080"


  # postgres:
  #   container_name: postgres_container
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: appfastfood
  #     POSTGRES_PASSWORD: 123456
  #     PGDATA: /data/postgres
  #   volumes:
  #       - postgres:/data/postgres
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - postgres
  #   restart: unless-stopped

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   ports:
  #     - "5050:80"
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
  #   networks:
  #     - postgres
  #   depends_on:
  #     - postgres

volumes:
  postgres:
  pgadmin:
networks:
    techchallenge-fastfood-net:
      driver: bridge
    postgres:
      driver: bridge