apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: root-node-reader-binding
  namespace: default
subjects:
  - kind: User
    name: root
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: node-reader
  apiGroup: rbac.authorization.k8s.io