apiVersion: v1
kind: Service
metadata:
  name: appfastfood
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  type: LoadBalancer
  selector:
    app: appfastfood
  ports:
    - port: 8080
      targetPort: 8080